name: Print Commit Message

on:
  push:
    branches:
      - 'main'

jobs: 
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: |
          echo "commit message:"
          git log -l --pretty=%B
